.TH "DL::Concept" 3 "Tue Dec 15 2020" "SDLL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DL::Concept
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Ontology\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBConcept\fP ()"
.br
.ti -1c
.RI "\fBConcept\fP (std::string &)"
.br
.ti -1c
.RI "\fB~Concept\fP ()"
.br
.ti -1c
.RI "void \fBsetName\fP (string &)"
.br
.ti -1c
.RI "std::string \fBgetName\fP () const"
.br
.ti -1c
.RI "std::vector< string > \fBgetIndividuals\fP () const"
.br
.ti -1c
.RI "void \fBaddIndividual\fP (string &)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "DL::Concept::Concept ()\fC [inline]\fP"

.SS "DL::Concept::Concept (std::string & name)"
========== CLASS CONCEPT ========== 
.SS "DL::Concept::~Concept ()\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void DL::Concept::addIndividual (string & s)"

.SS "std::vector< std::string > DL::Concept::getIndividuals () const"

.SS "std::string DL::Concept::getName () const"

.SS "void DL::Concept::setName (string & name)"


.SH "Author"
.PP 
Generated automatically by Doxygen for SDLL from the source code\&.
