.TH "DL::Role" 3 "Tue Dec 15 2020" "SDLL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DL::Role
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Ontology\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRole\fP ()"
.br
.ti -1c
.RI "\fBRole\fP (std::string &)"
.br
.ti -1c
.RI "\fB~Role\fP ()"
.br
.ti -1c
.RI "std::string \fBgetName\fP () const"
.br
.ti -1c
.RI "std::multimap< string, string > \fBgetPairs\fP () const"
.br
.ti -1c
.RI "void \fBinsert\fP (string &, string &)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "DL::Role::Role ()\fC [inline]\fP"

.SS "DL::Role::Role (std::string & name)"
========== CLASS ROLE ========== 
.SS "DL::Role::~Role ()\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "std::string DL::Role::getName () const"

.SS "std::multimap< string, string > DL::Role::getPairs () const"

.SS "void DL::Role::insert (string & s1, string & s2)"


.SH "Author"
.PP 
Generated automatically by Doxygen for SDLL from the source code\&.
