.TH "dl_scanner.hpp" 3 "Tue Dec 15 2020" "SDLL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dl_scanner.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <FlexLexer\&.h>\fP
.br
\fC#include <string>\fP
.br
\fC#include '\&.\&./parser\&.tab\&.hh'\fP
.br
\fC#include '\&.\&./location\&.hh'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDL::DL_Scanner\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBDL\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for SDLL from the source code\&.
