.TH "Ontology.cpp" 3 "Tue Dec 15 2020" "SDLL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ontology.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'Ontology\&.hpp'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "template<class K , class V > std::multimap< K, V >::const_iterator \fBfind_pair\fP (const std::multimap< K, V > &map, const std::pair< K, V > &pair)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "template<class K , class V > std::multimap<K, V>::const_iterator find_pair (const std::multimap< K, V > & map, const std::pair< K, V > & pair)"

.SH "Author"
.PP 
Generated automatically by Doxygen for SDLL from the source code\&.
