CONCEPT Allenatore, Calciatore;
ROLE allena, giocacon;
INDV pirlo, ronaldo, dybala, bonucci, agnelli, kompany;

%%

pirlo, kompany : Allenatore;
ronaldo, dybala : Calciatore;
(ronaldo, dybala), (bonucci, dybala) : giocacon;
(pirlo, ronaldo), (ronaldo, bonucci) : allena;

%%

//!Calciatore;
//!!!!!!!Allenatore;
//Allenatore CONJ notCalciatore;
Allenatore DISJ Calciatore;	// Negazione globale
//(!Allenatore) CONJ Calciatore;	// Negazione locale

/*Allenatore CONJ Calciatore SUBS AllenatoreDISJCalciatore;*/