CONCEPT Allenatore, Calciatore;
ROLE allena, giocacon;
INDV pirlo, ronaldo, dybala, bonucci, agnelli, kompany;

%%

pirlo, kompany : Allenatore;
ronaldo, dybala, bonucci: Calciatore;

(ronaldo, dybala), (bonucci, dybala): giocacon;
(pirlo, ronaldo), (ronaldo, pirlo) : allena;

%%
!Calciatore; //CONJ Allenatore;
//!(!(!(!(Calciatore CONJ Allenatore))));
//!Allenatore;
//Allenatore CONJ Calciatore;
//Allenatore DISJ Calciatore;
//Allenatore SUBS Calciatore;

(EX giocacon . Calciatore) SUBS (!Allenatore);

//EX allena . Calciatore;
//ALL giocacon . Calciatore;

%%
