.TH "DL" 3 "Tue Dec 15 2020" "SDLL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DL
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBConcept\fP"
.br
.ti -1c
.RI "class \fBDL_Driver\fP"
.br
.ti -1c
.RI "class \fBDL_Scanner\fP"
.br
.ti -1c
.RI "class \fBIndividual\fP"
.br
.ti -1c
.RI "class \fBOntology\fP"
.br
.ti -1c
.RI "class \fBRole\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for SDLL from the source code\&.
