.TH "DL::Individual" 3 "Tue Dec 15 2020" "SDLL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DL::Individual
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Ontology\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBIndividual\fP ()"
.br
.ti -1c
.RI "\fBIndividual\fP (std::string &)"
.br
.ti -1c
.RI "\fB~Individual\fP ()"
.br
.ti -1c
.RI "void \fBaddConcept\fP (string &)"
.br
.ti -1c
.RI "void \fBaddRole\fP (string &)"
.br
.ti -1c
.RI "std::string \fBgetName\fP () const"
.br
.ti -1c
.RI "std::vector< string > \fBgetConcepts\fP () const"
.br
.ti -1c
.RI "std::vector< string > \fBgetRoles\fP () const"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "DL::Individual::Individual ()\fC [inline]\fP"

.SS "DL::Individual::Individual (std::string & name)"
========== CLASS INDIVIDUAL ========== 
.SS "DL::Individual::~Individual ()\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void DL::Individual::addConcept (string & con)"

.SS "void DL::Individual::addRole (string & role)"

.SS "std::vector< string > DL::Individual::getConcepts () const"

.SS "std::string DL::Individual::getName () const"

.SS "std::vector< string > DL::Individual::getRoles () const"


.SH "Author"
.PP 
Generated automatically by Doxygen for SDLL from the source code\&.
