.TH "Ontology.hpp" 3 "Tue Dec 15 2020" "SDLL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ontology.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <string>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <map>\fP
.br
\fC#include <algorithm>\fP
.br
\fC#include <exception>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDL::Ontology\fP"
.br
.ti -1c
.RI "class \fBDL::Individual\fP"
.br
.ti -1c
.RI "class \fBDL::Role\fP"
.br
.ti -1c
.RI "class \fBDL::Concept\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBDL\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<class K , class V > std::multimap< K, V >::const_iterator \fBfind_pair\fP (const std::multimap< K, V > &map, const std::pair< K, V > &pair)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "template<class K , class V > std::multimap<K, V>::const_iterator find_pair (const std::multimap< K, V > & map, const std::pair< K, V > & pair)"

.SH "Author"
.PP 
Generated automatically by Doxygen for SDLL from the source code\&.
